version: "3"

tasks:
  run:
    desc: Start Toolcraft in development mode
    interactive: true
    cmds:
      - >-
        npx --yes --package node@22.18.0 --package npm@10.9.3
        --call 'npm --prefix starter install && npm --prefix starter run dev'
