import { defineToolcraft } from "@/toolcraft/runtime";

export const appSchema = defineToolcraft({
  canvas: {
    enabled: true,
    renderScale: true,
    size: { height: 360, unit: "px", width: 640 },
    sizing: { mode: "editable-output" },
    upload: true,
  },
  export: {
    png: { background: "include" },
  },
  panels: {
    controls: {
      sections: [
        {
          controls: {
            sourceImage: {
              assetKind: "image",
              defaultValue: null,
              label: "Source image",
              orderRole: "input",
              performanceReason:
                "Source dimensions determine image decode and GPU texture-upload workload.",
              performanceRole: "workload",
              target: "source.image",
              type: "fileDrop",
            },
          },
          title: "Source",
        },
        {
          controls: {
            columns: {
              defaultValue: 80,
              description: "Sets the horizontal image-sampling cell count.",
              label: "Columns",
              max: 200,
              min: 10,
              orderRole: "primary",
              performanceReason:
                "Column count is a primary particle-grid density workload control.",
              performanceRole: "workload",
              step: 1,
              target: "particle.columns",
              type: "slider",
            },
            rows: {
              defaultValue: 30,
              description: "Sets the vertical image-sampling cell count.",
              label: "Rows",
              max: 150,
              min: 5,
              orderRole: "primary",
              performanceReason:
                "Row count combines with Columns to define the visible grid density.",
              performanceRole: "workload",
              step: 1,
              target: "particle.rows",
              type: "slider",
            },
            maxColumnWidth: {
              defaultValue: 0.9,
              description:
                "Caps particle width as a fraction of one grid cell. At 1, the widest particles can touch adjacent columns when Column gap is zero.",
              label: "Maximum width",
              max: 1,
              min: 0.1,
              orderRole: "detail",
              performanceReason: "Max width updates one shader uniform during live drag.",
              performanceRole: "workload",
              step: 0.01,
              target: "particle.maxColumnWidth",
              type: "slider",
            },
            columnGap: {
              defaultValue: 0.05,
              description:
                "Reserves a minimum horizontal gap between particles. Set to zero to allow the widest particles to connect.",
              label: "Column gap",
              max: 0.5,
              min: 0,
              orderRole: "detail",
              performanceReason: "Column gap updates one shader uniform during live drag.",
              performanceRole: "workload",
              step: 0.005,
              target: "particle.columnGap",
              type: "slider",
            },
          },
          title: "Grid",
        },
        {
          controls: {
            particleWidth: {
              defaultValue: 1,
              description:
                "Controls how quickly brightness grows particle width. Values above 1 make more bright particles reach Maximum width.",
              label: "Width gain",
              max: 3,
              min: 0.1,
              orderRole: "strength",
              performanceReason: "Width gain updates particle mask geometry during live drag.",
              performanceRole: "workload",
              step: 0.01,
              target: "particle.width",
              type: "slider",
            },
            minWidth: {
              defaultValue: 0,
              description: "Keeps dark cells visible by enforcing a minimum width.",
              label: "Minimum width",
              max: 0.5,
              min: 0,
              orderRole: "detail",
              performanceReason:
                "Minimum width changes only particle mask geometry in the shader.",
              performanceRole: "workload",
              step: 0.01,
              target: "particle.minWidth",
              type: "slider",
            },
            softness: {
              defaultValue: 0.02,
              description: "Softens the centered left and right particle edges.",
              label: "Softness",
              max: 0.5,
              min: 0,
              orderRole: "advanced",
              performanceReason: "Softness changes smoothstep edge width in the shader.",
              performanceRole: "workload",
              step: 0.01,
              target: "particle.softness",
              type: "slider",
            },
          },
          title: "Particle Shape",
        },
        {
          controls: {
            colorMode: {
              defaultValue: "original",
              description:
                "Uses sampled source colors or one tint when Color Grouping is Off.",
              label: "Color mode",
              options: [
                { label: "Original", value: "original" },
                { label: "Tint", value: "tint" },
              ],
              orderRole: "primary",
              performanceReason: "Color mode switches a fragment-shader branch.",
              performanceRole: "workload",
              target: "particle.colorMode",
              type: "select",
            },
            tintColor: {
              defaultValue: "#FFFFFF",
              label: "Tint",
              orderRole: "color",
              performanceReason: "Tint changes one fragment-shader color uniform.",
              performanceRole: "workload",
              target: "particle.tintColor",
              type: "color",
              visibleWhen: { equals: "tint", target: "particle.colorMode" },
            },
            groupMode: {
              defaultValue: "off",
              description:
                "Overrides Color mode with four groups selected by luminance or hue.",
              label: "Color grouping",
              options: [
                { label: "Off", value: "off" },
                { label: "Brightness", value: "brightness" },
                { label: "Color", value: "color" },
              ],
              orderRole: "primary",
              performanceReason: "Grouping switches luminance and hue classification branches.",
              performanceRole: "workload",
              target: "particle.groupMode",
              type: "select",
            },
            groupColor1: {
              defaultValue: "#E63326",
              label: "Group 1 / Reds",
              orderRole: "color",
              performanceReason: "Group color changes one fragment-shader palette uniform.",
              performanceRole: "workload",
              target: "particle.groupColor1",
              type: "color",
              visibleWhen: { notEquals: "off", target: "particle.groupMode" },
            },
            groupColor2: {
              defaultValue: "#F2991A",
              label: "Group 2 / Oranges",
              orderRole: "color",
              performanceReason: "Group color changes one fragment-shader palette uniform.",
              performanceRole: "workload",
              target: "particle.groupColor2",
              type: "color",
              visibleWhen: { notEquals: "off", target: "particle.groupMode" },
            },
            groupColor3: {
              defaultValue: "#33B34D",
              label: "Group 3 / Greens",
              orderRole: "color",
              performanceReason: "Group color changes one fragment-shader palette uniform.",
              performanceRole: "workload",
              target: "particle.groupColor3",
              type: "color",
              visibleWhen: { notEquals: "off", target: "particle.groupMode" },
            },
            groupColor4: {
              defaultValue: "#334CCC",
              label: "Group 4 / Blues",
              orderRole: "color",
              performanceReason: "Group color changes one fragment-shader palette uniform.",
              performanceRole: "workload",
              target: "particle.groupColor4",
              type: "color",
              visibleWhen: { notEquals: "off", target: "particle.groupMode" },
            },
          },
          title: "Color Mapping",
        },
        {
          controls: {
            dotPatternBackground: {
              defaultValue: "#E6E6E6",
              label: "Pattern background",
              orderRole: "color",
              performanceReason: "Pattern background changes one shader color uniform.",
              performanceRole: "workload",
              target: "particle.dotPatternBackground",
              type: "color",
            },
            dotChance: {
              defaultValue: 0.3,
              description:
                "Sets the deterministic chance that a bright cell receives a dot pattern.",
              label: "Chance",
              max: 1,
              min: 0,
              orderRole: "strength",
              performanceReason: "Chance updates deterministic cell selection in the shader.",
              performanceRole: "workload",
              step: 0.01,
              target: "particle.dotChance",
              type: "slider",
            },
            dotDensity: {
              defaultValue: 3,
              description: "Sets the repeated dot count inside patterned particles.",
              label: "Density",
              max: 8,
              min: 1,
              orderRole: "detail",
              performanceReason: "Density changes repeated dot frequency in the fragment shader.",
              performanceRole: "workload",
              step: 1,
              target: "particle.dotDensity",
              type: "slider",
            },
            dotSize: {
              defaultValue: 0.5,
              description: "Sets each repeated dot diameter inside patterned particles.",
              label: "Dot size",
              max: 0.9,
              min: 0.1,
              orderRole: "detail",
              performanceReason: "Dot size updates one smooth circle-mask uniform.",
              performanceRole: "workload",
              step: 0.01,
              target: "particle.dotSize",
              type: "slider",
            },
          },
          title: "Dot Pattern",
        },
        {
          controls: {
            grainAmount: {
              applicability: { mode: "always" },
              defaultValue: 0,
              description:
                "Adds deterministic texture to luminance, particle size, and particle color.",
              label: "Amount",
              max: 0.5,
              min: 0,
              orderRole: "strength",
              performanceReason:
                "Grain amount enables one deterministic hash used by geometry and color.",
              performanceRole: "workload",
              sliderValueKind: "continuous",
              step: 0.01,
              target: "particle.grainAmount",
              type: "slider",
            },
            grainScale: {
              applicability: { mode: "always" },
              defaultValue: 1,
              description: "Controls the size of the deterministic grain texture.",
              label: "Scale",
              max: 8,
              min: 0.25,
              orderRole: "detail",
              performanceReason:
                "Grain scale changes only hash coordinates in the fragment shader.",
              performanceRole: "workload",
              sliderValueKind: "continuous",
              step: 0.25,
              target: "particle.grainScale",
              type: "slider",
            },
            grainSeed: {
              applicability: { mode: "always" },
              defaultValue: 1,
              description: "Chooses a repeatable grain arrangement.",
              label: "Seed",
              max: 100,
              min: 1,
              orderRole: "detail",
              performanceReason:
                "Seed changes a constant-cost deterministic hash offset.",
              performanceRole: "workload",
              sliderValueKind: "continuous",
              step: 1,
              target: "particle.grainSeed",
              type: "slider",
            },
          },
          title: "Grain",
        },
        {
          controls: {
            includeBackground: {
              defaultValue: true,
              description: "Includes the selected background in preview and image export.",
              label: "Include",
              orderRole: "primary",
              performanceReason: "Background inclusion changes only final GPU compositing.",
              performanceRole: "responsiveness",
              target: "export.includeBackground",
              type: "switch",
            },
            background: {
              defaultValue: "#000000",
              label: false,
              orderRole: "color",
              performanceReason: "Background color changes one final-composite uniform.",
              performanceRole: "responsiveness",
              target: "appearance.background",
              type: "color",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["includeBackground", "background"],
              layout: "inline",
            },
          ],
          title: "Background",
        },
        {
          controls: {
            imageFormat: {
              defaultValue: "png",
              label: "Format",
              options: [
                { label: "PNG", value: "png" },
                { label: "JPG", value: "jpg" },
              ],
              orderRole: "primary",
              performanceReason: "Format changes only final browser image encoding.",
              performanceRole: "responsiveness",
              target: "export.image.format",
              type: "select",
            },
            imageResolution: {
              defaultValue: "4k",
              label: "Resolution",
              options: [
                { label: "2K", value: "2k" },
                { label: "4K", value: "4k" },
                { label: "8K", value: "8k" },
              ],
              orderRole: "detail",
              performanceReason: "Resolution determines export GPU and canvas allocation.",
              performanceRole: "workload",
              target: "export.image.resolution",
              type: "select",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["imageFormat", "imageResolution"],
              layout: "inline",
            },
          ],
          title: "Image Export",
        },
        {
          actionGroup: "secondary",
          controls: {
            outputActions: {
              actions: [
                {
                  icon: "upload-simple",
                  label: "Export PNG",
                  role: "export-image",
                  value: "export.png",
                },
              ],
              target: "actions.output",
              type: "panelActions",
            },
          },
          title: "Export",
        },
      ],
      title: "Particle Grid Effect",
    },
  },
  persistence: { storage: "none" },
  settingsTransfer: {
    appId: "particle-grid-effect",
    enabled: "auto",
    fileName: "particle-grid-effect-settings.json",
  },
  toolbar: {
    history: true,
    radar: true,
    theme: true,
    zoom: true,
  },
});
